name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies for routing_node
      run: |
        cd nodes/routing_node
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for strategy_service
      run: |
        cd nodes/strategy_service
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for routing_node
      run: |
        cd nodes/routing_node
        source venv/bin/activate
        pytest tests

    - name: Run tests for strategy_service
      run: |
        cd nodes/strategy_service
        source venv/bin/activate
        pytest tests
