name: ChatGPT Integration

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Nom du fichier à modifier'
        required: true
      content:
        description: 'Contenu du fichier'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "ChatGPT Bot"
          git config --global user.email "chatgpt@openai.com"

      - name: Modifier le fichier
        run: |
          echo "${{ github.event.inputs.content }}" > ${{ github.event.inputs.file_name }}
          git add ${{ github.event.inputs.file_name }}
          git commit -m "Update ${{ github.event.inputs.file_name }} via ChatGPT"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
